#!/bin/bash

# SPDX-FileCopyrightText: 2018 - 2023 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

DIR="$(dirname "${0}")"

#
# Augment the Vim/Neovim en.utf-8.add file with this repo's word list.
#

function update_vim {
  local vimspelldir=${HOME}/.vim/spell/
  mkdir -p "${vimspelldir}"
  if [ -f "${vimspelldir}"/en.utf-8.add ]; then
    cat "${vimspelldir}"/en.utf-8.add > "${TMP}"
    cat "${DIR}"/spell/en.utf-8.add >> "${TMP}"
    sort -d -f -u "${TMP}" > "${vimspelldir}"/en.utf-8.add
  else
    cp "${DIR}"/spell/en.utf-8.add "${vimspelldir}"/en.utf-8.add
  fi
}

function update_neovim {
  local nvimspelldir=${HOME}/.config/nvim/spell/
  mkdir -p "${nvimspelldir}"
  if [ -f "${nvimspelldir}"/en.utf-8.add ]; then
    cat "${nvimspelldir}"/en.utf-8.add > "${TMP}"
    cat "${DIR}"/spell/en.utf-8.add >> "${TMP}"
    sort -d -f -u "${TMP}" > "${nvimspelldir}"/en.utf-8.add
  else
    cp "${DIR}"/spell/en.utf-8.add "${nvimspelldir}"/en.utf-8.add
  fi
}

TMP="$(mktemp)"
trap 'rm -f "${TMP}"; exit' INT TERM ERR EXIT

update_vim
update_neovim
