#! /bin/bash
set -eu

DIR="$(dirname "${0}")"

cd "${DIR}"/spell

if command -v vim > /dev/null; then
  vim -E -c "mkspell! en.utf-8.add" +qall
elif command -v nvim > /dev/null; then
  nvim -E -c "mkspell! en.utf-8.add" +qall
else
  echo "ERROR: 'vim' and 'nvim' not installed. Exiting."
  exit 3
fi
