#! /bin/bash
set -eu

function install_vim {
  local vimspelldir=${HOME}/.vim/spell
  mkdir -p "${vimspelldir}"
  cp -vf spell/en.utf-8.add{,.spl} "${vimspelldir}/"
}

function install_neovim {
  local nvimspelldir=${HOME}/.config/nvim/spell
  mkdir -p "${nvimspelldir}"
  cp -vf spell/en.utf-8.add{,.spl} "${nvimspelldir}/"
}

install_vim
install_neovim
