#!/bin/bash

# SPDX-FileCopyrightText: 2018 - 2023 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

DIR="$(dirname "${0}")"

function install_vim {
  local vimspelldir=${HOME}/.vim/spell
  mkdir -p "${vimspelldir}"
  cp -vf "${DIR}"/spell/en.utf-8.add{,.spl} "${vimspelldir}/"
}

function install_neovim {
  local nvimspelldir=${HOME}/.config/nvim/spell
  mkdir -p "${nvimspelldir}"
  cp -vf "${DIR}"/spell/en.utf-8.add{,.spl} "${nvimspelldir}/"
}

install_vim
install_neovim
