#!/bin/bash

# SPDX-FileCopyrightText: 2018 - 2022 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

function uninstall_vim {
  local vimspelldir="${HOME}/.vim/spell"
  if [ -d "${vimspelldir}" ]; then
    rm -vf "${vimspelldir}"/en.utf-8.add{,.spl}
    rmdir --ignore-fail-on-non-empty "${vimspelldir}"
  fi
}

function uninstall_neovim {
  local nvimspelldir="${HOME}/.config/nvim/spell"
  if [ -d "${nvimspelldir}" ]; then
    rm -vf "${nvimspelldir}"/en.utf-8.add{,.spl}
    rmdir --ignore-fail-on-non-empty "${nvimspelldir}"
  fi
}

uninstall_vim
uninstall_neovim
