#!/bin/bash

# SPDX-FileCopyrightText: 2021 - 2023 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

DIR="$(dirname "${0}")"

#
# Augment this repo's word list with the Vim/Neovim en.utf-8.add file.
#

function update_word_list {
  local vimspelldir=${HOME}/.vim/spell/
  local neovimspelldir=${HOME}/.config/nvim/spell/

  cat "${DIR}"/spell/en.utf-8.add > "${TMP}"

  if [ -f "${vimspelldir}"/en.utf-8.add ]; then
    cat "${vimspelldir}"/en.utf-8.add >> "${TMP}"
  fi

  if [ -f "${neovimspelldir}"/en.utf-8.add ]; then
    cat "${neovimspelldir}"/en.utf-8.add >> "${TMP}"
  fi

  mv "${DIR}"/spell/en.utf-8.add spell/en.utf-8.add_"$(date +%Y%m%d-%H%M%S)".bak
  sort -d -f -u "${TMP}" > "${DIR}"/spell/en.utf-8.add
}

TMP="$(mktemp)"
trap 'rm -f "${TMP}"; exit' INT TERM ERR EXIT

update_word_list
