#! /bin/bash
set -eu

#
# Augment this repo's word list with the Vim/Neovim en.utf-8.add file.
#

function update_word_list {
  local vimspelldir=${HOME}/.vim/spell/
  local neovimspelldir=${HOME}/.config/nvim/spell/
  
  cat spell/en.utf-8.add > "${TMP}"

  mkdir -p "${vimspelldir}"
  if [ -f "${vimspelldir}"/en.utf-8.add ]; then
    cat "${vimspelldir}"/en.utf-8.add >> "${TMP}"
  fi

  mkdir -p "${neovimspelldir}"
  if [ -f "${neovimspelldir}"/en.utf-8.add ]; then
    cat "${neovimspelldir}"/en.utf-8.add >> "${TMP}"
  fi
 
  mv spell/en.utf-8.add spell/en.utf-8.add.bak
  sort -d -f -u "${TMP}" > spell/en.utf-8.add
}

TMP="$(mktemp)"
trap 'rm -f "${TMP}"; exit' INT TERM ERR EXIT

update_word_list
